"""Exercise the production UI with the real API and software WebGL.

GLASSWORK_URL selects an already running server. Screenshots are unedited browser
captures for the README, and the JSON report records the verified interactions.
"""
import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
BASE = os.environ.get('GLASSWORK_URL', 'http://127.0.0.1:8002')
OUT = ROOT / 'docs/images'
OUT.mkdir(parents=True, exist_ok=True)
checks = []
def passed(name):
    checks.append(name)
    print('PASS', name, flush=True)

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, args=['--use-angle=swiftshader','--enable-unsafe-swiftshader'])
    page = browser.new_page(viewport={'width':1600,'height':1100})
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(BASE, wait_until='networkidle')
    ready = page.get_by_role('button', name='Inspect prompt', exact=True)
    expect(ready).to_be_enabled()
    expect(page.get_by_label('Active model', exact=True)).to_have_value('transformer')
    expect(page.locator('.journey-title')).to_contain_text('A character becomes a vector.')
    def state():
        return page.evaluate("async()=> (await fetch('/api/sessions/'+sessionStorage.getItem('glasswork-session'))).json()")
    def stage(name):
        page.get_by_role('navigation',name='Model stages').get_by_role('button',name=name).click()
        expect(page.locator('.inspector h2')).to_have_text(name)
    def screenshot(name):
        page.evaluate('document.activeElement?.blur()')
        page.screenshot(path=str(OUT/name), full_page=True)
    baseline = state()
    assert baseline['parameter_count'] == baseline['trainable_parameter_count'] == 28186
    sid = page.evaluate("sessionStorage.getItem('glasswork-session')")
    canvas = page.locator('canvas')
    first = canvas.screenshot()
    page.wait_for_timeout(350)
    assert first != canvas.screenshot()
    page.get_by_label('Operation progress',exact=True).fill('90')
    page.wait_for_timeout(800)
    frozen = canvas.screenshot()
    page.wait_for_timeout(250)
    assert frozen == canvas.screenshot(), 'Scrubbed operation should hold its frame'
    screenshot('character-journey.png')
    page.get_by_label('Dimension window',exact=True).select_option('24')
    expect(page.locator('.journey-caption')).to_contain_text(['token ID 21 → embedding lookup','Dimensions 24–31 of 32'])
    passed('Live character animation, manual scrub and all 32 embedding dimensions')
    for name in ['Position','Q · K · V','Attention','Projection','Probabilities']:
        stage(name)
        page.get_by_label('Operation progress',exact=True).fill('75')
    stage('Attention')
    page.get_by_label('Transformer layer',exact=True).select_option('1')
    page.get_by_label('Attention head',exact=True).select_option('1')
    expect(page.locator('.journey-title')).to_contain_text('LAYER 2 · HEAD 2')
    page.get_by_text('Inside this transformer block',exact=True).click()
    expect(page.locator('.block-details .vector')).to_have_count(7)
    page.get_by_label('Selected character',exact=True).select_option('0')
    expect(page.locator('.attention-list code')).to_have_text('100.00%')
    page.get_by_label('Selected character',exact=True).select_option('6')
    page.locator('.block-details').evaluate('el=>el.open=false')
    passed('Six operations, both layers, both heads, causal mask and feed-forward values')
    page.get_by_role('button',name='Architecture',exact=True).click()
    expect(page.locator('.world-label')).to_have_count(6)
    page.get_by_role('button',name='Reset camera',exact=True).click()
    page.wait_for_timeout(1000)
    screenshot('model-architecture.png')
    stage('Embedding')
    page.get_by_role('button',name='Play walkthrough',exact=True).click()
    expect(page.get_by_role('button',name='Architecture',exact=True)).to_have_attribute('aria-pressed','true')
    expect(page.locator('.world-label')).to_have_count(6)
    expect(page.locator('.journey-title')).to_have_count(0)
    expect(page.locator('.inspector h2')).to_have_text('Position',timeout=10000)
    page.get_by_role('button',name='Pause walkthrough',exact=True).click()
    page.get_by_role('button',name='Follow character',exact=True).click()
    page.get_by_role('button',name='Play walkthrough',exact=True).click()
    expect(page.get_by_role('button',name='Follow character',exact=True)).to_have_attribute('aria-pressed','true')
    expect(page.locator('.journey-title')).to_be_visible()
    expect(page.locator('.world-label')).to_have_count(0)
    page.get_by_role('button',name='Pause walkthrough',exact=True).click()
    page.get_by_role('button',name='Reduce motion',exact=True).click()
    page.wait_for_timeout(900)
    frozen=canvas.screenshot()
    page.wait_for_timeout(300)
    assert frozen==canvas.screenshot(), 'Reduced motion must freeze the operation'
    page.get_by_role('button',name='Reduce motion',exact=True).click()
    passed('Architecture, guided playback and reduced-motion frame stability')
    page.get_by_role('button',name='Experiment',exact=True).click()
    temperature = page.get_by_label('Temperature',exact=False)
    temperature.fill('0')
    generate = page.get_by_role('button',name='Generate 64 characters')
    expect(generate).to_be_enabled()
    assert page.locator('.lab-probabilities small').all_text_contents().count('100.0%')==1
    assert state()['fingerprint']==baseline['fingerprint']
    temperature.fill('0.7')
    expect(generate).to_be_enabled()
    generate.click()
    expect(generate).to_be_enabled()
    sample = page.locator('.sample-box pre').inner_text()
    assert len(sample)>=64 and sample.count(' ')>4, sample
    generate.click()
    expect(generate).to_be_enabled()
    assert page.locator('.sample-box pre').inner_text()==sample
    screenshot('sampling-lab.png')
    passed('Live probabilities, unchanged weights and reproducible word-like generation')
    page.get_by_role('button',name='Learning lab',exact=True).click()
    page.get_by_role('button',name='Random weights',exact=True).click()
    expect(page.locator('.training-progress')).to_contain_text('0 total updates')
    initial_loss = state()['history'][-1]['train']
    page.get_by_role('button',name='Train 25 steps',exact=True).click()
    expect(page.locator('.training-progress')).to_contain_text('25 steps completed this run',timeout=60000)
    assert state()['step']==25
    assert state()['history'][-1]['train']<initial_loss
    expect(page.locator('.weight-matrix .changed')).to_have_count(832)
    expect(page.locator('.recharts-surface')).to_be_visible()
    screenshot('learning-lab.png')
    page.route('**/train',lambda route:(page.wait_for_timeout(200),route.continue_()))
    page.get_by_role('button',name='Train 25 steps',exact=True).click()
    page.get_by_role('button',name='Stop',exact=True).click()
    expect(page.get_by_role('button',name='Train 25 steps',exact=True)).to_be_enabled(timeout=20000)
    assert 25<state()['step']<50
    page.unroute('**/train')
    page.get_by_role('button',name='Restore checkpoint',exact=True).click()
    expect(page.locator('.training-progress')).to_contain_text('1200 total updates')
    assert state()['fingerprint']==baseline['fingerprint']
    passed('Full-model learning lowers loss; stop, changed weights and exact checkpoint restore')
    page.get_by_role('button',name='Sampling lab',exact=True).click()
    page.route('**/inspect',lambda route:route.fulfill(status=503,content_type='application/json',body='{"detail":"Temporary test outage"}'),times=1)
    temperature.fill('1.1')
    expect(page.locator('.lab-message')).to_contain_text('Temporary test outage')
    page.get_by_role('button',name='Retry connection',exact=True).click()
    expect(generate).to_be_enabled()
    assert state()['fingerprint']==baseline['fingerprint']
    assert page.evaluate("sessionStorage.getItem('glasswork-session')")==sid
    page.keyboard.press('Escape')
    passed('Retry after a transient failure preserves the learner’s model')
    prompt=page.get_by_label('Model prompt',exact=True)
    prompt.fill('the blue bird')
    ready.click()
    expect(ready).to_be_enabled()
    page.get_by_role('link',name='Embedding space').click()
    page.wait_for_function("document.body.dataset.ready === 'true'")
    page.get_by_role('button',name='Explore A − B + C').click()
    expect(page.locator('#neighbors strong').first).to_have_text('queen')
    page.get_by_label('Arithmetic progress',exact=True).fill('100')
    expect(page.locator('#arithmetic-status')).to_contain_text('Sum complete')
    page.wait_for_timeout(400)
    screenshot('embedding-arithmetic.png')
    expect(page.locator('#component-chart > div')).to_have_count(8)
    page.get_by_label('Scale A',exact=True).fill('0')
    page.get_by_label('Scale B',exact=True).fill('0')
    page.get_by_label('Scale C',exact=True).fill('1')
    page.get_by_role('button',name='Explore weighted sum').click()
    page.get_by_label('Arithmetic progress',exact=True).fill('40')
    expect(page.locator('#arithmetic-status')).to_contain_text('2 / 3')
    page.get_by_label('Arithmetic progress',exact=True).fill('90')
    expect(page.locator('#arithmetic-status')).to_contain_text('3 / 3')
    page.get_by_label('Scale C',exact=True).fill('0')
    page.get_by_role('button',name='Explore weighted sum').click()
    expect(page.get_by_role('alert')).to_contain_text('zero')
    page.get_by_label('Scale A',exact=True).fill('2')
    page.get_by_label('Scale B',exact=True).fill('-0.5')
    page.get_by_label('Scale C',exact=True).fill('0.25')
    page.get_by_role('button',name='Explore weighted sum').click()
    expect(page.get_by_role('alert')).to_be_hidden()
    page.get_by_role('button',name='Replay addition',exact=True).click()
    frame=page.locator('canvas').screenshot()
    page.wait_for_timeout(350)
    assert frame!=page.locator('canvas').screenshot()
    passed('Real analogy, scalar sums, zero-vector validation, zero-length segments and replay')
    page.get_by_role('button',name='Reduce motion',exact=True).click()
    page.wait_for_timeout(500)
    frozen=page.locator('canvas').screenshot()
    page.wait_for_timeout(300)
    assert frozen==page.locator('canvas').screenshot()
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.locator('canvas').evaluate("c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true}))")
    expect(page.locator('.webgl-fallback')).to_be_visible()
    page.get_by_role('button',name='Explore weighted sum').click()
    expect(page.locator('#neighbors li')).to_have_count(8)
    page.locator('.brain-header .brand').click()
    expect(ready).to_be_enabled()
    expect(prompt).to_have_value('the blue bird')
    assert page.evaluate("sessionStorage.getItem('glasswork-session')")==sid
    assert state()['fingerprint']==baseline['fingerprint']
    page.get_by_role('button',name='Experiment',exact=True).click()
    expect(temperature).to_have_value('1.1')
    page.keyboard.press('Escape')
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.get_by_label('Operation progress',exact=True).fill('90')
    page.wait_for_timeout(400)
    screenshot('mobile-journey.png')
    passed('Mobile views, embedding GPU fallback, and navigation retains model, prompt and temperature')
    page.get_by_label('Active model',exact=True).select_option('team')
    expect(ready).to_be_enabled()
    assert state()['parameter_count']==640
    page.get_by_label('Active model',exact=True).select_option('transformer')
    expect(ready).to_be_enabled()
    assert state()['fingerprint']==baseline['fingerprint']
    page.evaluate("async()=>fetch('/api/sessions/'+sessionStorage.getItem('glasswork-session'),{method:'DELETE'})")
    prompt.fill('the cat ')
    ready.click()
    expect(page.get_by_role('alert')).to_contain_text('expired')
    page.get_by_role('button',name='Reconnect',exact=True).click()
    expect(ready).to_be_enabled()
    assert page.evaluate("sessionStorage.getItem('glasswork-session')")!=sid
    assert state()['parameter_count']==28186
    page.locator('canvas').evaluate("c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true}))")
    expect(page.locator('.diagram-stations button')).to_have_count(6)
    passed('Model switching, expired-session replacement and model GPU fallback')
    assert not errors,errors
    passed('No uncaught browser errors')
    page.evaluate("async()=>{for(const kind of ['team','transformer']) {const sid=sessionStorage.getItem('glasswork-session-'+kind); if(sid) await fetch('/api/sessions/'+sid,{method:'DELETE'});}}")
    (ROOT/'artifacts/expanded-browser.json').write_text(json.dumps({'result':'PASS','checks':checks,'page_errors':errors,'sample':sample},indent=2)+'\n')
    browser.close()
